### ISSUE TITLE
Hey Lucho! Una pregunta sobre geocoding Lima

### ISSUE THREAD

**Issue by paolorivas** [lescobedo21/GeocodingInLima#1]
Hola Lucho que tal,

Te habla Paolo Rivas, soy peruano y Estudiante de Data Journalism en Columbia. Estoy utilizando tu codigo en R para geocodificar una data de la municipalidad de Miraflores en CSV. he aplicado tu script para este caso, pero R me reporta un error que nose como solucionar. Ideas?

Muchas gracias! Super cool que subas esta codigo btw. 

![screen shot 2016-11-10 at 5 51 19 pm](https://cloud.githubusercontent.com/assets/19495863/20197605/6a73f8e4-a76e-11e6-9f2b-7a7eec7df329.png)

**Comment by lescobedo21** [comment]
Hola Paolo,

Gracias por usar el codigo. Estoy en roadtrip, pero vuelvo a Illinois el
domingo. Mandame el pantallazo de tu error.

**Comment by paolorivas** [comment]
Lucho gracias por la respuesta!

Logre solucionar el error. Era simplemente que no habia hecho el require de
ggmap. Simple. Si todo sale bien te dejo un link con lo que estoy
trabajando. Bueno siempre mantener el contacto. Muy pocos trabajamos en
geocoding en peru! Un abrazo.
